services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DATABASE}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USERNAME}'
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: 'redis:latest'
    ports:
      - '${REDIS_PORT}:6379'

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - 'KAFKA_CFG_NODE_ID=0'
      - 'KAFKA_CFG_PROCESS_ROLES=controller,broker'
      - 'KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093'
      - 'KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      - 'KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093'
      - 'KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER'
      - 'KAFKA_CLIENT_USERS=${KAFKA_CLIENT_USERS}'
      - 'KAFKA_CLIENT_PASSWORDS=${KAFKA_CLIENT_PASSWORDS}'
      - 'KAFKA_CONTROLLER_USER=${KAFKA_CONTROLLER_USER}'
      - 'KAFKA_CONTROLLER_PASSWORD=${KAFKA_CONTROLLER_PASSWORD}'

  auth:
    build:
      context: ./src/main/java/app/auth
      dockerfile: Dockerfile
    ports:
      - "${AUTH_PORT}:8000"
    environment:
      - APP_PATH=auth
    volumes:
      - ./auth:/app/auth
    depends_on:
      - postgres
      - redis

